export const DWCITY = 'DWCITY'
export const IMG = 'IMG'
export const CITY = 'CITY'
export const GETCITY = 'GETCITY'
export const SERCITY = 'SERCITY'
export const HOTCITY = 'HOTCITY'
export const SERSHOP = 'SERSHOP'